name: Run Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Install dependencies
        run: pip install pytest  # Install pytest

      - name: Run test for hw-1
        run: pytest ./myfile_test.py  # Run your tests

      - name: Run test for hw-2
        run:  pytest ./HW-2/test_cases.py
            
